AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Retrieval Lambda with sentence-transformers

Parameters:
  Environment:
    Type: String
    Default: dev
    AllowedValues: [dev, staging, prod]
    Description: Environment name
  
  S3Bucket:
    Type: String
    Description: S3 bucket containing the Lambda deployment package
    Default: retrieval-lambda-deployment-bucket
  
  S3Key:
    Type: String
    Default: retrieval-lambda/function.zip
    Description: S3 key for the Lambda deployment package
  
  HFToken:
    Type: String
    NoEcho: true
    Description: Hugging Face API token for embeddings
    Default: ""
  
  EmbeddingsBucket:
    Type: String
    Description: S3 bucket for storing embeddings
    Default: legal-system-embeddings-v1
  
Resources:
  # Lambda Execution Role
  RetrievalLambdaRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
      Policies:
        - PolicyName: S3AccessPolicy
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - s3:GetObject
                  - s3:PutObject
                  - s3:DeleteObject
                  - s3:ListBucket
                Resource:
                  - !Sub "arn:aws:s3:::${EmbeddingsBucket}"
                  - !Sub "arn:aws:s3:::${EmbeddingsBucket}/*"


  # API Gateway V2 (HTTP API)
  RetrievalApi:
    Type: AWS::ApiGatewayV2::Api
    Properties:
      Name: !Sub "retrieval-api-${Environment}"
      ProtocolType: HTTP
      CorsConfiguration:
        AllowOrigins:
          - "*"
        AllowMethods:
          - GET
          - POST
          - PUT
          - DELETE
          - OPTIONS
        AllowHeaders:
          - Content-Type
          - Authorization
          - Origin
          - X-Requested-With

  # API Gateway Integration
  LambdaIntegration:
    Type: AWS::ApiGatewayV2::Integration
    Properties:
      ApiId: !Ref RetrievalApi
      IntegrationType: AWS_PROXY
      IntegrationUri: !Sub "arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${RetrievalLambdaFunction.Arn}/invocations"
      PayloadFormatVersion: "2.0"

  # API Gateway Routes
  ApiRoute:
    Type: AWS::ApiGatewayV2::Route
    Properties:
      ApiId: !Ref RetrievalApi
      RouteKey: "ANY /{proxy+}"
      Target: !Sub "integrations/${LambdaIntegration}"

  # API Gateway Stage
  ApiStage:
    Type: AWS::ApiGatewayV2::Stage
    Properties:
      ApiId: !Ref RetrievalApi
      StageName: "$default"
      AutoDeploy: true

  # Lambda Permission
  LambdaInvokePermission:
    Type: AWS::Lambda::Permission
    Properties:
      FunctionName: !Ref RetrievalLambdaFunction
      Action: lambda:InvokeFunction
      Principal: apigateway.amazonaws.com
      SourceArn: !Sub "arn:aws:execute-api:${AWS::Region}:${AWS::AccountId}:${RetrievalApi}/*/*"

  # Lambda Function
  RetrievalLambdaFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub retrieval-lambda-${Environment}
      Runtime: python3.11
      Architectures:
        - arm64
      CodeUri: 
        Bucket: !Ref S3Bucket
        Key: !Ref S3Key
      Handler: lambda_function.lambda_handler
      MemorySize: 512
      Timeout: 30
      Role: !GetAtt RetrievalLambdaRole.Arn
      # No layers needed - numpy included in package
      Environment:
        Variables:
          ENVIRONMENT: !Ref Environment
          HF_TOKEN: !Ref HFToken


Outputs:
  ApiUrl:
    Description: "API Gateway endpoint URL"
    Value: !Sub "https://${RetrievalApi}.execute-api.${AWS::Region}.amazonaws.com/"
    Export:
      Name: !Sub "${AWS::StackName}-ApiUrl"

  RetrievalLambdaFunctionArn:
    Description: "ARN of the Retrieval Lambda Function"
    Value: !GetAtt RetrievalLambdaFunction.Arn
    Export:
      Name: !Sub "${AWS::StackName}-RetrievalLambdaFunctionArn"

  RetrievalLambdaFunctionName:
    Description: "Name of the Retrieval Lambda Function"
    Value: !Ref RetrievalLambdaFunction
    Export:
      Name: !Sub "${AWS::StackName}-RetrievalLambdaFunctionName"